### ISSUE TITLE
Make a difference between 'using' and 'require' clauses in the AST

### ISSUE THREAD

**Issue by alexarchambault** [VirtuslabRnD/using_directives#15]
Right now, looking at [`ast9.txt`](https://github.com/VirtuslabRnD/using_directives/blob/2e8ad0fa2eaba0649adbe4cbd685635fca0b763e/src/test/resources/parser_tests/asts/ast9.txt), it seems there's no way to know whether it originates from a `using` or a `require` clause (apart maybe using positions found on some AST classes?).

Maybe `SettingDef` could have a `type` or `kind` field, returing `"using"` or `"require"` (or even maybe `"@using"` or `"@require"`).

**Comment by romanowski** [comment]
We have retired the idea of `require` directives.
